[build]
publish = "dariush/public"
command = "hugo --source=dariush --theme=../.. --baseURL=https://dariush.in"

[build.environment]
HUGO_VERSION = "0.28"

[context.dev]
command = "hugo --source=dariush --theme=../.. --baseURL=https://dev.dariush.in"
